name: flutterconf
description: The official app for FlutterConf.
publish_to: none
version: 1.1.13+23

environment:
  sdk: ">=3.9.2 <4.0.0"
  flutter: ">=3.35.4 <4.0.0"

dependencies:
  bloc: ^9.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  font_awesome_flutter: ^10.7.0
  hydrated_bloc: ^10.0.0
  image: ^4.5.4
  image_picker: ^1.2.0
  intl: ^0.20.0
  json_annotation: ^4.9.0
  path_provider: ^2.0.0
  pub_semver: ^2.1.4
  shorebird_code_push: ^2.0.2
  url_launcher: ^6.0.0
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  google_sign_in: ^6.2.2
  cloud_firestore: ^5.6.12
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.1.4
  go_router: ^17.1.0
  shared_preferences: ^2.5.4

dev_dependencies:
  bloc_lint: ^0.3.2
  build_runner: ^2.4.12
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  very_good_analysis: ^9.0.0
  mocktail: ^1.0.4
  bloc_test: ^10.0.0

flutter:
  assets:
    - assets/
    - shorebird.yaml
  uses-material-design: true
